apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-test-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-test-pod
  template:
    metadata:
      labels:
        app: k8s-test-pod
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: secret-volume
      - name: configmap-volume
        configMap:
          name: configmap-volume
          # defaultMode: 511
      containers:
      - name: web
        image: asia-east1-docker.pkg.dev/round-center-422013-u2/leo-k8s-demo/k8stest:latest
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8080
        envFrom:
        - secretRef:
            name: secret-env
        # envFrom:
        # - configMapRef:
        #     name: configmap-env
        volumeMounts:
          - mountPath: /app/config/
            name: secret-volume
        volumeMounts:
          - mountPath: /app/config/
            name: configmap-volume