apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-test-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-test-pod
  template:
    metadata:
      labels:
        app: k8s-test-pod
    spec:
      containers:
      - name: web
        image: k8stest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8080