apiVersion: v1
kind: Pod
metadata:
  name: k8s-test-pod
  labels:
    app: k8s-test-pod
spec:
  containers:
    - name: web
      image: k8stest:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080
      livenessProbe:
        httpGet:
          path: /healthcheck
          port: 8080