apiVersion: v1
kind: Service
metadata:
  name: k8s-test-service
spec:
  selector:
    app: k8s-test-pod
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 31000
  type: NodePort